bookshelf:
  title: Bookshelf
  version: 0.0.1
  some-number: 10

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:./testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  liquibase:
    drop-first: true
  security:
    user:
      name: bookshelf
      password: bookshelf

